### ISSUE TITLE
Work with node 12?

### ISSUE THREAD

**Issue by watchtower314** [jerson/react-native-fast-openpgp#14]
Hi!
Thank you for this library, it has been very helpful to us :)

I wanted to ask about this library working with node12; we want to upgrade our project from node10 to node12, but it seems like `react-native-fast-openpgp` will not work with node12, do you have any plans for upgrading? Or perhaps there's something my team and I can do to make it work for us?

Thank you for your time!

**Comment by jerson** [comment]
Hi @watchtower314 thanks for report the issue I didnt know that, I think I can help with that, please can you share which version are you using for react native in order to make sure that will work for you team

**Comment by watchtower314** [comment]
Hi @jerson, thank you for the quick response!
here's a screenshot with versions we're using:

![Screen Shot 2020-12-02 at 9 19 10](https://user-images.githubusercontent.com/30501647/100884331-5961ba80-347f-11eb-9e0c-359cf27e8098.png)

Thanks!

**Comment by jerson** [comment]
@watchtower314 thanks for that, and please which react-native-fast-openpgp version are you using (please be sure that you are using latest 1.6.0), and which error are you getting please

**Comment by watchtower314** [comment]
@jerson Thank you for your patience!
We're using the latest version 
![Screen Shot 2020-12-08 at 3 31 17](https://user-images.githubusercontent.com/30501647/101459017-b1784100-3905-11eb-8181-726fe256da46.png)

and here is the error message we're getting

<img width="1428" alt="Screen Shot 2020-12-07 at 21 28 01" src="https://user-images.githubusercontent.com/30501647/101459074-c2c14d80-3905-11eb-8618-b82d94f2a110.png">

**Comment by jerson** [comment]
Hi @watchtower314 i have been testing here and for me is working well,

![Screen Shot 2020-12-08 at 10 47 12](https://user-images.githubusercontent.com/325780/101505813-bf988280-3942-11eb-85fd-d4f02944347e.png)
![Screen Shot 2020-12-08 at 10 48 00](https://user-images.githubusercontent.com/325780/101505936-db9c2400-3942-11eb-87d9-744daf0c0c10.png)

im using **1.6.3** released today with more archs in the framework, so maybe could be related to this

```json
  "dependencies": {
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-fast-openpgp": "^1.6.3"
  }
```
this is the sample project created
[projectname.zip](https://github.com/jerson/react-native-fast-openpgp/files/5660294/projectname.zip)

if you can create a sample project with the issue please can you add here, because for now i cant reproduce it

**Comment by watchtower314** [comment]
@jerson Yes, 1.6.3 works for us! Thank you very much!
